// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_fields.proto

/*
Package user_fields is a generated protocol buffer package.

It is generated from these files:
	user_fields.proto

It has these top-level messages:
	UpdateFieldsByUidReq
	GetFieldsByUidReq
	GetFieldsByUidResp
	BatchGetFieldsByUidReq
	BatchGetFieldsByUidResp
	InsertFieldsByUidReq
	InsertFieldsByUidResp
	UpdateFieldsByJsonReq
	GetFieldsByJsonReq
	GetFieldsByJsonResp
	GetFieldsRequest
	GetFieldsReply
	UpdateFieldsRequest
	UpdateFieldsReply
	GetMembersFieldsRequest
	GetMembersFieldsReply
*/
package user_fields

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	//"git.qutoutiao.net/gopher/qurpc"
	"github.com/hprose/hprose-golang/io"
	"github.com/hprose/hprose-golang/rpc"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_OK                ErrorCode = 0
	ErrorCode_INVALID_ARGUMENT  ErrorCode = 40000
	ErrorCode_ACCOUNT_NOT_EXIST ErrorCode = 40004
	ErrorCode_SYSTEM_ERROR      ErrorCode = 50000
)

var ErrorCode_name = map[int32]string{
	0:     "OK",
	40000: "INVALID_ARGUMENT",
	40004: "ACCOUNT_NOT_EXIST",
	50000: "SYSTEM_ERROR",
}
var ErrorCode_value = map[string]int32{
	"OK":                0,
	"INVALID_ARGUMENT":  40000,
	"ACCOUNT_NOT_EXIST": 40004,
	"SYSTEM_ERROR":      50000,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateFieldsByUidReq struct {
	MemberId string `protobuf:"bytes,1,opt,name=memberId" json:"memberId,omitempty"`
	AppName  string `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	JsonVal  string `protobuf:"bytes,3,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *UpdateFieldsByUidReq) Reset()                    { *m = UpdateFieldsByUidReq{} }
func (m *UpdateFieldsByUidReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateFieldsByUidReq) ProtoMessage()               {}
func (*UpdateFieldsByUidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateFieldsByUidReq) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *UpdateFieldsByUidReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *UpdateFieldsByUidReq) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type GetFieldsByUidReq struct {
	MemberId string   `protobuf:"bytes,1,opt,name=memberId" json:"memberId,omitempty"`
	AppName  string   `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	Fields   []string `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
}

func (m *GetFieldsByUidReq) Reset()                    { *m = GetFieldsByUidReq{} }
func (m *GetFieldsByUidReq) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsByUidReq) ProtoMessage()               {}
func (*GetFieldsByUidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetFieldsByUidReq) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetFieldsByUidReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *GetFieldsByUidReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetFieldsByUidResp struct {
	MemberId string `protobuf:"bytes,1,opt,name=memberId" json:"memberId,omitempty"`
	AppName  string `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	JsonVal  string `protobuf:"bytes,3,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *GetFieldsByUidResp) Reset()                    { *m = GetFieldsByUidResp{} }
func (m *GetFieldsByUidResp) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsByUidResp) ProtoMessage()               {}
func (*GetFieldsByUidResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetFieldsByUidResp) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetFieldsByUidResp) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *GetFieldsByUidResp) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type BatchGetFieldsByUidReq struct {
	MemberIds []int64  `protobuf:"varint,1,rep,packed,name=memberIds" json:"memberIds,omitempty"`
	AppName   string   `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	Fields    []string `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
}

func (m *BatchGetFieldsByUidReq) Reset()                    { *m = BatchGetFieldsByUidReq{} }
func (m *BatchGetFieldsByUidReq) String() string            { return proto.CompactTextString(m) }
func (*BatchGetFieldsByUidReq) ProtoMessage()               {}
func (*BatchGetFieldsByUidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BatchGetFieldsByUidReq) GetMemberIds() []int64 {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

func (m *BatchGetFieldsByUidReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *BatchGetFieldsByUidReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BatchGetFieldsByUidResp struct {
	AppName string `protobuf:"bytes,1,opt,name=appName" json:"appName,omitempty"`
	JsonVal string `protobuf:"bytes,2,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *BatchGetFieldsByUidResp) Reset()                    { *m = BatchGetFieldsByUidResp{} }
func (m *BatchGetFieldsByUidResp) String() string            { return proto.CompactTextString(m) }
func (*BatchGetFieldsByUidResp) ProtoMessage()               {}
func (*BatchGetFieldsByUidResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BatchGetFieldsByUidResp) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *BatchGetFieldsByUidResp) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type InsertFieldsByUidReq struct {
	AppName string `protobuf:"bytes,1,opt,name=appName" json:"appName,omitempty"`
	JsonVal string `protobuf:"bytes,2,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *InsertFieldsByUidReq) Reset()                    { *m = InsertFieldsByUidReq{} }
func (m *InsertFieldsByUidReq) String() string            { return proto.CompactTextString(m) }
func (*InsertFieldsByUidReq) ProtoMessage()               {}
func (*InsertFieldsByUidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InsertFieldsByUidReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *InsertFieldsByUidReq) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type InsertFieldsByUidResp struct {
}

func (m *InsertFieldsByUidResp) Reset()                    { *m = InsertFieldsByUidResp{} }
func (m *InsertFieldsByUidResp) String() string            { return proto.CompactTextString(m) }
func (*InsertFieldsByUidResp) ProtoMessage()               {}
func (*InsertFieldsByUidResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UpdateFieldsByJsonReq struct {
	MemberId int64  `protobuf:"varint,1,opt,name=memberId" json:"memberId,omitempty"`
	JsonVal  string `protobuf:"bytes,2,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *UpdateFieldsByJsonReq) Reset()                    { *m = UpdateFieldsByJsonReq{} }
func (m *UpdateFieldsByJsonReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateFieldsByJsonReq) ProtoMessage()               {}
func (*UpdateFieldsByJsonReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateFieldsByJsonReq) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *UpdateFieldsByJsonReq) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type GetFieldsByJsonReq struct {
	MemberId int64    `protobuf:"varint,1,opt,name=memberId" json:"memberId,omitempty"`
	Fields   []string `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty"`
}

func (m *GetFieldsByJsonReq) Reset()                    { *m = GetFieldsByJsonReq{} }
func (m *GetFieldsByJsonReq) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsByJsonReq) ProtoMessage()               {}
func (*GetFieldsByJsonReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetFieldsByJsonReq) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *GetFieldsByJsonReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetFieldsByJsonResp struct {
	MemberId int64  `protobuf:"varint,1,opt,name=memberId" json:"memberId,omitempty"`
	JsonVal  string `protobuf:"bytes,2,opt,name=jsonVal" json:"jsonVal,omitempty"`
}

func (m *GetFieldsByJsonResp) Reset()                    { *m = GetFieldsByJsonResp{} }
func (m *GetFieldsByJsonResp) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsByJsonResp) ProtoMessage()               {}
func (*GetFieldsByJsonResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetFieldsByJsonResp) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *GetFieldsByJsonResp) GetJsonVal() string {
	if m != nil {
		return m.JsonVal
	}
	return ""
}

type GetFieldsRequest struct {
	MemberId string `protobuf:"bytes,1,opt,name=memberId" json:"memberId,omitempty"`
	// 指定需要获取的key
	// 支持两级目录
	// 如可以 a.b 表示获取a字段下的key为b的值
	Name []string `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
}

func (m *GetFieldsRequest) Reset()                    { *m = GetFieldsRequest{} }
func (m *GetFieldsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsRequest) ProtoMessage()               {}
func (*GetFieldsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetFieldsRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetFieldsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type GetFieldsReply struct {
	// 查询到的key和值
	Values map[string]string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetFieldsReply) Reset()                    { *m = GetFieldsReply{} }
func (m *GetFieldsReply) String() string            { return proto.CompactTextString(m) }
func (*GetFieldsReply) ProtoMessage()               {}
func (*GetFieldsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetFieldsReply) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type UpdateFieldsRequest struct {
	MemberId string `protobuf:"bytes,1,opt,name=memberId" json:"memberId,omitempty"`
	// 需要更新的key和value
	Values map[string]string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UpdateFieldsRequest) Reset()                    { *m = UpdateFieldsRequest{} }
func (m *UpdateFieldsRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateFieldsRequest) ProtoMessage()               {}
func (*UpdateFieldsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UpdateFieldsRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *UpdateFieldsRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type UpdateFieldsReply struct {
}

func (m *UpdateFieldsReply) Reset()                    { *m = UpdateFieldsReply{} }
func (m *UpdateFieldsReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateFieldsReply) ProtoMessage()               {}
func (*UpdateFieldsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetMembersFieldsRequest struct {
	MemberId []string `protobuf:"bytes,1,rep,name=memberId" json:"memberId,omitempty"`
	// 指定需要获取的key
	// 支持两级目录
	// 如可以 a.b 表示获取a字段下的key为b的值
	Name []string `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
}

func (m *GetMembersFieldsRequest) Reset()                    { *m = GetMembersFieldsRequest{} }
func (m *GetMembersFieldsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMembersFieldsRequest) ProtoMessage()               {}
func (*GetMembersFieldsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetMembersFieldsRequest) GetMemberId() []string {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *GetMembersFieldsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type GetMembersFieldsReply struct {
	// 查询到的key和值
	Values map[string]*GetFieldsReply `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetMembersFieldsReply) Reset()                    { *m = GetMembersFieldsReply{} }
func (m *GetMembersFieldsReply) String() string            { return proto.CompactTextString(m) }
func (*GetMembersFieldsReply) ProtoMessage()               {}
func (*GetMembersFieldsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetMembersFieldsReply) GetValues() map[string]*GetFieldsReply {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateFieldsByUidReq)(nil), "user_fields.UpdateFieldsByUidReq")
	proto.RegisterType((*GetFieldsByUidReq)(nil), "user_fields.GetFieldsByUidReq")
	proto.RegisterType((*GetFieldsByUidResp)(nil), "user_fields.GetFieldsByUidResp")
	proto.RegisterType((*BatchGetFieldsByUidReq)(nil), "user_fields.BatchGetFieldsByUidReq")
	proto.RegisterType((*BatchGetFieldsByUidResp)(nil), "user_fields.BatchGetFieldsByUidResp")
	proto.RegisterType((*InsertFieldsByUidReq)(nil), "user_fields.InsertFieldsByUidReq")
	proto.RegisterType((*InsertFieldsByUidResp)(nil), "user_fields.InsertFieldsByUidResp")
	proto.RegisterType((*UpdateFieldsByJsonReq)(nil), "user_fields.UpdateFieldsByJsonReq")
	proto.RegisterType((*GetFieldsByJsonReq)(nil), "user_fields.GetFieldsByJsonReq")
	proto.RegisterType((*GetFieldsByJsonResp)(nil), "user_fields.GetFieldsByJsonResp")
	proto.RegisterType((*GetFieldsRequest)(nil), "user_fields.GetFieldsRequest")
	proto.RegisterType((*GetFieldsReply)(nil), "user_fields.GetFieldsReply")
	proto.RegisterType((*UpdateFieldsRequest)(nil), "user_fields.UpdateFieldsRequest")
	proto.RegisterType((*UpdateFieldsReply)(nil), "user_fields.UpdateFieldsReply")
	proto.RegisterType((*GetMembersFieldsRequest)(nil), "user_fields.GetMembersFieldsRequest")
	proto.RegisterType((*GetMembersFieldsReply)(nil), "user_fields.GetMembersFieldsReply")
	proto.RegisterEnum("user_fields.ErrorCode", ErrorCode_name, ErrorCode_value)
	io.Register((*UpdateFieldsByUidReq)(nil), "Passport_UserFields_UpdateFieldsByUidReq", "json")
	io.Register((*GetFieldsByUidReq)(nil), "Passport_UserFields_GetFieldsByUidReq", "json")
	io.Register((*GetFieldsByUidResp)(nil), "Passport_UserFields_GetFieldsByUidResp", "json")
	io.Register((*BatchGetFieldsByUidReq)(nil), "Passport_UserFields_BatchGetFieldsByUidReq", "json")
	io.Register((*BatchGetFieldsByUidResp)(nil), "Passport_UserFields_BatchGetFieldsByUidResp", "json")
	io.Register((*InsertFieldsByUidReq)(nil), "Passport_UserFields_InsertFieldsByUidReq", "json")
	io.Register((*InsertFieldsByUidResp)(nil), "Passport_UserFields_InsertFieldsByUidResp", "json")
	io.Register((*UpdateFieldsByJsonReq)(nil), "Passport_UserFields_UpdateFieldsByJsonReq", "json")
	io.Register((*GetFieldsByJsonReq)(nil), "Passport_UserFields_GetFieldsByJsonReq", "json")
	io.Register((*GetFieldsByJsonResp)(nil), "Passport_UserFields_GetFieldsByJsonResp", "json")
	io.Register((*GetFieldsRequest)(nil), "Passport_UserFields_GetFieldsRequest", "json")
	io.Register((*GetFieldsReply)(nil), "Passport_UserFields_GetFieldsReply", "json")
	io.Register((*UpdateFieldsRequest)(nil), "Passport_UserFields_UpdateFieldsRequest", "json")
	io.Register((*UpdateFieldsReply)(nil), "Passport_UserFields_UpdateFieldsReply", "json")
	io.Register((*GetMembersFieldsRequest)(nil), "Passport_UserFields_GetMembersFieldsRequest", "json")
	io.Register((*GetMembersFieldsReply)(nil), "Passport_UserFields_GetMembersFieldsReply", "json")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.

// Client API for UserFields service

type UserFieldsClientService struct {
	// 查询用户属性
	GetFields func(*GetFieldsRequest) (*GetFieldsReply, error)
	// 查询多个用户属性
	GetMembersFields func(*GetMembersFieldsRequest) (*GetMembersFieldsReply, error)
	// 更新指定用户属性
	UpdateFields func(*UpdateFieldsRequest) (*UpdateFieldsReply, error)
	// 更新指定用户通过json
	UpdateFieldsByJson  func(*UpdateFieldsByJsonReq) (*UpdateFieldsReply, error)
	GetFieldsByJson     func(*GetFieldsByJsonReq) (*GetFieldsByJsonResp, error)
	UpdateFieldsByUid   func(*UpdateFieldsByUidReq) (*UpdateFieldsReply, error)
	GetFieldsByUid      func(*GetFieldsByUidReq) (*GetFieldsByUidResp, error)
	BatchGetFieldsByUid func(*BatchGetFieldsByUidReq) (*BatchGetFieldsByUidResp, error)
	InsertFieldsByUid   func(*InsertFieldsByUidReq) (*InsertFieldsByUidResp, error)
}

// Server API for UserFields service

type UserFieldsServer interface {
	// 查询用户属性
	GetFields(*GetFieldsRequest, *rpc.HTTPContext) (*GetFieldsReply, error)
	// 查询多个用户属性
	GetMembersFields(*GetMembersFieldsRequest, *rpc.HTTPContext) (*GetMembersFieldsReply, error)
	// 更新指定用户属性
	UpdateFields(*UpdateFieldsRequest, *rpc.HTTPContext) (*UpdateFieldsReply, error)
	// 更新指定用户通过json
	UpdateFieldsByJson(*UpdateFieldsByJsonReq, *rpc.HTTPContext) (*UpdateFieldsReply, error)
	GetFieldsByJson(*GetFieldsByJsonReq, *rpc.HTTPContext) (*GetFieldsByJsonResp, error)
	UpdateFieldsByUid(*UpdateFieldsByUidReq, *rpc.HTTPContext) (*UpdateFieldsReply, error)
	GetFieldsByUid(*GetFieldsByUidReq, *rpc.HTTPContext) (*GetFieldsByUidResp, error)
	BatchGetFieldsByUid(*BatchGetFieldsByUidReq, *rpc.HTTPContext) (*BatchGetFieldsByUidResp, error)
	InsertFieldsByUid(*InsertFieldsByUidReq, *rpc.HTTPContext) (*InsertFieldsByUidResp, error)
}

// var _UserFields_serviceDesc = qrpc.ServiceDesc{
// 	ServiceName: "UserFields",
// 	Methods: []qrpc.MethodDesc{
// 		{MethodName: "GetFields"},
// 		{MethodName: "GetMembersFields"},
// 		{MethodName: "UpdateFields"},
// 		{MethodName: "UpdateFieldsByJson"},
// 		{MethodName: "GetFieldsByJson"},
// 		{MethodName: "UpdateFieldsByUid"},
// 		{MethodName: "GetFieldsByUid"},
// 		{MethodName: "BatchGetFieldsByUid"},
// 		{MethodName: "InsertFieldsByUid"},
// 	},
// }

// func RegisterUserFieldsServer(s *qrpc.Server, srv UserFieldsServer) {
// 	s.RegisterService(&_UserFields_serviceDesc, srv)
// }

func init() { proto.RegisterFile("user_fields.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x36, 0x04, 0x32, 0xa9, 0xc0, 0x99, 0xb4, 0x4d, 0x14, 0xa0, 0x0d, 0xa6, 0x12, 0x15,
	0x42, 0x41, 0x94, 0x0b, 0x70, 0x41, 0x4d, 0x9b, 0x86, 0xb4, 0x24, 0x29, 0xae, 0x13, 0x15, 0x54,
	0x29, 0xb8, 0x78, 0xab, 0x16, 0xd2, 0x78, 0xeb, 0x75, 0x91, 0xf2, 0x02, 0x9c, 0x78, 0x06, 0x1e,
	0x82, 0x0b, 0x3d, 0x72, 0xe0, 0xc4, 0xa9, 0xcf, 0xc0, 0x93, 0xa0, 0xd8, 0x6e, 0xe2, 0x9f, 0x8d,
	0x5d, 0x55, 0xb9, 0x79, 0x76, 0x66, 0xbf, 0xf9, 0xe6, 0x67, 0x67, 0x0c, 0xd9, 0x53, 0x46, 0xac,
	0xee, 0xc1, 0x11, 0xe9, 0x19, 0xac, 0x4c, 0x2d, 0xd3, 0x36, 0x31, 0xe3, 0x3b, 0x52, 0x0e, 0x60,
	0xb6, 0x4d, 0x0d, 0xdd, 0x26, 0x1b, 0x8e, 0x5c, 0x19, 0xb4, 0x8f, 0x0c, 0x95, 0x9c, 0x60, 0x11,
	0x6e, 0x1d, 0x93, 0xe3, 0x7d, 0x62, 0xd5, 0x8d, 0x82, 0x50, 0x12, 0x96, 0xd3, 0xea, 0x48, 0xc6,
	0x02, 0xdc, 0xd4, 0x29, 0x6d, 0xea, 0xc7, 0xa4, 0x20, 0x3a, 0xaa, 0x0b, 0x71, 0xa8, 0xf9, 0xcc,
	0xcc, 0x7e, 0x47, 0xef, 0x15, 0x24, 0x57, 0xe3, 0x89, 0x8a, 0x0e, 0xd9, 0x1a, 0xb1, 0xa7, 0xe2,
	0x64, 0x1e, 0x52, 0x2e, 0xf9, 0x82, 0x54, 0x92, 0x96, 0xd3, 0xaa, 0x27, 0x29, 0x06, 0x60, 0xd8,
	0x05, 0xa3, 0x53, 0x0f, 0xe4, 0x10, 0xe6, 0x2b, 0xba, 0xfd, 0xe9, 0x30, 0x1a, 0xcd, 0x3d, 0x48,
	0x5f, 0x20, 0xb3, 0x82, 0x50, 0x92, 0x96, 0x25, 0x75, 0x7c, 0x70, 0x85, 0x78, 0x1a, 0x90, 0xe7,
	0x7a, 0x62, 0xd4, 0x0f, 0x26, 0x4c, 0x24, 0x2e, 0x06, 0x89, 0x6f, 0xc2, 0x6c, 0xbd, 0xcf, 0x88,
	0x15, 0xa6, 0x7d, 0x15, 0xac, 0x3c, 0xcc, 0x71, 0xb0, 0x18, 0x55, 0x1a, 0x30, 0x17, 0x6c, 0xa7,
	0x4d, 0x66, 0xf6, 0x79, 0xa5, 0x96, 0x82, 0x65, 0x98, 0xe0, 0xe7, 0x4d, 0xa0, 0xa4, 0x97, 0xc1,
	0x1a, 0x27, 0x53, 0x0c, 0x24, 0x73, 0x0b, 0x72, 0x11, 0x24, 0x4e, 0x77, 0x5c, 0x8e, 0x56, 0x05,
	0xe4, 0x11, 0x98, 0x4a, 0x4e, 0x4e, 0x09, 0xb3, 0x63, 0xfb, 0x0c, 0xe1, 0x7a, 0xdf, 0x2d, 0xfc,
	0x90, 0x92, 0xf3, 0xad, 0x7c, 0x17, 0xe0, 0xb6, 0x0f, 0x84, 0xf6, 0x06, 0xf8, 0x1a, 0x52, 0x5f,
	0xf5, 0xde, 0x29, 0x71, 0xbb, 0x27, 0xb3, 0xf2, 0xa8, 0xec, 0x7f, 0xbc, 0x41, 0xe3, 0x72, 0xc7,
	0xb1, 0xac, 0xf6, 0x6d, 0x6b, 0xa0, 0x7a, 0xd7, 0x8a, 0x2f, 0x21, 0xe3, 0x3b, 0x46, 0x19, 0xa4,
	0x2f, 0x64, 0xe0, 0xb1, 0x19, 0x7e, 0xe2, 0x2c, 0xdc, 0x70, 0x4c, 0xbd, 0x80, 0x5c, 0xe1, 0x95,
	0xf8, 0x42, 0x50, 0x7e, 0x0a, 0x90, 0xf3, 0x57, 0xee, 0x32, 0x61, 0xad, 0x8f, 0xf8, 0x8a, 0x0e,
	0xdf, 0x27, 0x01, 0xbe, 0x1c, 0xb4, 0x69, 0x93, 0xce, 0x41, 0x36, 0xe8, 0x85, 0xf6, 0x06, 0x4a,
	0x1d, 0xf2, 0x35, 0x62, 0x37, 0x1c, 0x92, 0x2c, 0x2e, 0x18, 0x29, 0xb1, 0x46, 0xbf, 0x04, 0x98,
	0x8b, 0x62, 0x0d, 0x4b, 0xb5, 0x11, 0x2a, 0x55, 0x39, 0x5c, 0xaa, 0xe8, 0x1d, 0x6e, 0xf0, 0x9d,
	0xa4, 0xe0, 0x9f, 0xf9, 0x83, 0xcf, 0xac, 0xdc, 0x8d, 0x69, 0x09, 0x5f, 0x66, 0x1e, 0xef, 0x42,
	0xba, 0x6a, 0x59, 0xa6, 0xb5, 0x66, 0x1a, 0x04, 0x53, 0x20, 0xb6, 0xb6, 0xe4, 0x6b, 0x38, 0x0f,
	0x72, 0xbd, 0xd9, 0x59, 0x7d, 0x5b, 0x5f, 0xef, 0xae, 0xaa, 0xb5, 0x76, 0xa3, 0xda, 0xd4, 0xe4,
	0xdf, 0x67, 0x22, 0xe6, 0x21, 0xbb, 0xba, 0xb6, 0xd6, 0x6a, 0x37, 0xb5, 0x6e, 0xb3, 0xa5, 0x75,
	0xab, 0xbb, 0xf5, 0x1d, 0x4d, 0xfe, 0x73, 0x26, 0x22, 0xc2, 0xcc, 0xce, 0xfb, 0x1d, 0xad, 0xda,
	0xe8, 0x56, 0x55, 0xb5, 0xa5, 0xca, 0xe7, 0xdf, 0xa4, 0x95, 0x1f, 0x29, 0x80, 0x36, 0x23, 0x96,
	0xeb, 0x18, 0x6b, 0x90, 0x1e, 0xb1, 0xc0, 0xfb, 0x93, 0xd8, 0x39, 0xe9, 0x2f, 0xc6, 0x91, 0xc7,
	0x3d, 0xe7, 0x4d, 0x05, 0xd2, 0x86, 0x4b, 0x09, 0x59, 0x75, 0x61, 0x95, 0xe4, 0xdc, 0xe3, 0x36,
	0xcc, 0xf8, 0x3b, 0x05, 0x4b, 0x49, 0xad, 0x5a, 0x5c, 0x88, 0xb1, 0x18, 0x22, 0xee, 0x02, 0x46,
	0x27, 0x1d, 0x2a, 0x13, 0x6f, 0x8d, 0xc6, 0x57, 0x22, 0xb2, 0x06, 0x77, 0x42, 0xa3, 0x0a, 0x17,
	0xf9, 0x99, 0x1b, 0x63, 0x96, 0xe2, 0x0d, 0x18, 0xc5, 0x4e, 0xf0, 0xad, 0x38, 0x23, 0x1b, 0x1f,
	0xc4, 0xd0, 0x75, 0xd7, 0x43, 0x22, 0xdb, 0x77, 0xbe, 0x31, 0xe6, 0x82, 0x2e, 0x4c, 0xe2, 0xe2,
	0x21, 0x2e, 0xc6, 0xea, 0x19, 0xc5, 0x8f, 0x90, 0xe3, 0x2c, 0x3e, 0x7c, 0x18, 0xb8, 0xc7, 0x5f,
	0xc2, 0xc5, 0xa5, 0x64, 0x23, 0x46, 0xf1, 0x03, 0x64, 0x23, 0xfb, 0x2b, 0x94, 0x0c, 0xde, 0xae,
	0x0c, 0xb5, 0x1a, 0x77, 0x05, 0x56, 0x9e, 0xfe, 0x15, 0x73, 0xdb, 0x3a, 0x63, 0xd4, 0xb4, 0xec,
	0xbd, 0xf1, 0x4b, 0x39, 0x17, 0x85, 0x7f, 0x5c, 0xc5, 0x7e, 0xca, 0xf9, 0x2d, 0x7b, 0xfe, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0xe2, 0x21, 0xd3, 0x6d, 0xab, 0x09, 0x00, 0x00,
}
